apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tessa-staging

resources:
- ../../base

commonLabels:
  environment: staging

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: tessa.staging.chowie.dev
    - op: replace
      path: /spec/tls/0/hosts/0
      value: tessa.staging.chowie.dev
    - op: replace
      path: /spec/tls/0/secretName
      value: tessa-staging-tls
  target:
    kind: Ingress
    name: tessa-ingress

images:
- digest: sha256:4f8b233f0e05a18aca964c8b6491375bf70a4b2ed56a401181b575248c1e4f5b
  name: ghcr.io/chowieuk/tessa-frontend
  newName: ghcr.io/chowieuk/tessa-frontend
