apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tessa-staging

resources:
- ../../base

commonLabels:
  environment: staging

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: tessa.staging.chowie.dev
    - op: replace
      path: /spec/tls/0/hosts/0
      value: tessa.staging.chowie.dev
    - op: replace
      path: /spec/tls/0/secretName
      value: tessa-staging-tls
  target:
    kind: Ingress
    name: tessa-ingress

images:
- digest: sha256:7bb03eda08b66e43aeee952b23992432a0b7dadd7258ab1e4080e6215eb4fb7d
  name: ghcr.io/chowieuk/tessa-frontend
  newName: ghcr.io/chowieuk/tessa-frontend
