apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tessa-staging

resources:
- ../../base

commonLabels:
  environment: staging

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: tessa.staging.chowie.dev
    - op: replace
      path: /spec/tls/0/hosts/0
      value: tessa.staging.chowie.dev
    - op: replace
      path: /spec/tls/0/secretName
      value: tessa-staging-tls
  target:
    kind: Ingress
    name: tessa-ingress

images:
- digest: sha256:c104d0146251c309f1c02c31289fb46fd5d8124fc2a0ce6131fbb800f5cde292
  name: ghcr.io/chowieuk/tessa-frontend
  newName: ghcr.io/chowieuk/tessa-frontend
