apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tessa-staging

resources:
- ../../base

commonLabels:
  environment: staging

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: tessa.staging.chowie.dev
    - op: replace
      path: /spec/tls/0/hosts/0
      value: tessa.staging.chowie.dev
    - op: replace
      path: /spec/tls/0/secretName
      value: tessa-staging-tls
  target:
    kind: Ingress
    name: tessa-ingress

images:
- digest: sha256:b022296b0d9645da6592276b0ff54b253eb2940000ff0212629e513b17322fe6
  name: ghcr.io/chowieuk/tessa-frontend
  newName: ghcr.io/chowieuk/tessa-frontend
