apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maze-racer-staging

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - target:
      kind: Ingress
      name: maze-racer-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: maze.staging.chowie.dev
      - op: replace
        path: /spec/tls/0/hosts/0
        value: maze.staging.chowie.dev
      - op: replace
        path: /spec/tls/0/secretName
        value: maze-staging-tls
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging

images:
  - name: ghcr.io/chowieuk/maze-racer-backend
    digest: sha256:eb7e31ba664e68f4919cdbfd1dab9d49ca09b1342436a494586c00d0742fd93c
  - name: ghcr.io/chowieuk/maze-racer-frontend
    digest: sha256:cd48512a57625aa0779f67d7d9ef274e6ac2888c491a3c1d9aac17c1bfff1240
