apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
- ../../base

commonLabels:
  environment: prod

images:
- digest: sha256:e70eb4cb27ae8d9eab1c2f7c5161a82ad4577b157f66a9cef718880ed899482e
  name: ghcr.io/chowieuk/chowie-dev
- name: ghcr.io/chowieuk/hit-counter-api
  newTag: latest
