apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
- ../../base

commonLabels:
  environment: prod

images:
- digest: sha256:2db33a9e1857f8355616e1a693ae8a3383087df6e4dbf7e6a35c6f7e34ff194a
  name: ghcr.io/chowieuk/chowie-dev
- name: ghcr.io/chowieuk/hit-counter-api
  newTag: latest
