apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-staging

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - target:
      kind: Ingress
      name: blog-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.chowie.dev
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.chowie.dev
      - op: replace
        path: /spec/tls/0/secretName
        value: blog-staging-tls

images:
  - name: ghcr.io/chowieuk/chowie-dev
    digest: sha256:22dc0d5ede7afab035d8a9bb96e684ba7a4ccbc438d0273250a7b90a62c3071c
  - name: ghcr.io/chowieuk/hit-counter-api
    newTag: latest # This'll be updated in the next release.
