# apps/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maze-racer-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"

    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   proxy_set_header Upgrade $http_upgrade;
    #   proxy_set_header Connection "upgrade";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - maze.chowie.dev
      secretName: maze-chowie-uk-tls
  rules:
    - host: maze.chowie.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: maze-racer-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maze-racer-frontend-service
                port:
                  number: 80
