apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-frontend
  template:
    metadata:
      labels:
        app: astro-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: site
          image: ghcr.io/chowieuk/chowie-dev@sha256:516cbdc7e1d825f97a385cab5a28864399dc898321266f46588b67066468cc40
          ports:
            - containerPort: 80
