apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-frontend
  template:
    metadata:
      labels:
        app: astro-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: site
          image: ghcr.io/chowieuk/chowie-dev@sha256:7c73f279c8314aeb97e91ccdf013fbed950fa303e9df3e7b29c3fc2ae84db37d
          ports:
            - containerPort: 80
