apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-frontend
  template:
    metadata:
      labels:
        app: astro-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: site
          image: ghcr.io/chowieuk/chowie-dev@sha256:73fbc48895e363e1a90ed428d4d0e44a2173bef68c3195da6260359a6124587a
          ports:
            - containerPort: 80
