apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-frontend
  template:
    metadata:
      labels:
        app: astro-frontend
    spec:
      containers:
        - name: site
          image: ghcr.io/chowieuk/chowie-dev:latest
          ports:
            - containerPort: 80
