apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tessa

resources:
  - ../../base

commonLabels:
  environment: prod

replicas:
  - name: tessa-frontend
    count: 1

images:
  - name: ghcr.io/chowieuk/tessa-frontend
    digest: sha256:ef8fdc62d2549803c2c95b705e36b8c0a44a20576d0ddc480229b606cf99fb48
