apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tessa

resources:
- ../../base

commonLabels:
  environment: prod

replicas:
- count: 1
  name: tessa-frontend

images:
- digest: sha256:b022296b0d9645da6592276b0ff54b253eb2940000ff0212629e513b17322fe6
  name: ghcr.io/chowieuk/tessa-frontend
